services:
  - type: web
    name: pt-record-system
    env: node
    buildCommand: npm run build:all
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    disk:
      name: persistent-disk
      mountPath: /opt/render/project/persistent
      sizeGB: 1
